### ISSUE TITLE
Persistent waveform broken in Processing 3

### ISSUE THREAD

**Issue by trinitronx** [fadookie/Super3dvisualizer#1]
As noticed by [Bobby Lewis via YouTube comments][1], the persistence or 3D 'tracer' style draw behavior seems broken when running this on Processing version 3.x.

I was able to reproduce on:

- OS: Linux / Ubuntu `18.04` (`bionic`)
- Processing version: `3.5.4`

[1]: https://www.youtube.com/watch?v=2Z99TtxGjds&lc=Ugwg3d5Nv2XP7qIr9hl4AaABAg

**Comment by fadookie** [comment]
Welp if someone wants to fix it, have at it and I'll merge the PR. I don't really have time to do this myself.

I had an older version of this set up with a more normal looking 3D wireframe and it still looked pretty cool, I think it's on the git history somewhere.

**Comment by fadookie** [comment]
Fixed in master https://github.com/fadookie/Super3dvisualizer/commit/7f8a2551da2a917b88bdc2009eff04519374fd84
